package com.url.shortener.service;

import com.url.shortener.repository.ShortenerRepository;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

/**
 * Service layer for handling URL shortening and retrieval operations.
 * <p>
 * This service acts as an intermediary between the API layer and the repository layer,
 * providing business logic for URL shortening operations. It combines the shortened
 * URL identifiers generated by the repository with a configurable domain to create
 * complete shortened URLs.
 * </p>
 * <p>
 * Key responsibilities:
 * <ul>
 *     <li>Generating complete shortened URLs with domain prefix</li>
 *     <li>Delegating URL storage and retrieval to the repository layer</li>
 *     <li>Managing the short URL domain configuration</li>
 * </ul>
 * </p>
 *
 * @version 1.0
 * @since 2025-11-20
 */
@Service
public class ShortenerService
{
    /**
     * The domain prefix for shortened URLs.
     * <p>
     * This value is injected from application properties with the key "short_url.domain".
     * If not configured, it defaults to "http://localhost:8080/".
     * The domain is prepended to the short URL identifier to create the complete shortened URL.
     * </p>
     */
    @Value("${short_url.domain:http://localhost:8080/}")
    private String shortUrlDomain;

    /**
     * Repository for performing data access operations on URL mappings.
     */
    private final ShortenerRepository shortenerRepository;

    /**
     * Constructs a new ShortenerService with the specified repository.
     *
     * @param shortenerRepository the repository for URL data access operations
     */
    public ShortenerService(ShortenerRepository shortenerRepository)
    {
        this.shortenerRepository = shortenerRepository;
    }

    /**
     * Generates a complete shortened URL for the given long URL.
     * <p>
     * This method delegates to the repository to create a unique short URL identifier,
     * then combines it with the configured domain to produce the complete shortened URL
     * that can be shared with users.
     * </p>
     *
     * @param longUrl the original long URL to be shortened
     * @return the complete shortened URL including the domain prefix
     * @throws IllegalStateException if URL ID generation fails
     */
    public String getShortUrl(String longUrl)
    {
        return shortUrlDomain + shortenerRepository.shortenUrl(longUrl);
    }

    /**
     * Retrieves the original long URL associated with a shortened URL identifier.
     * <p>
     * This method extracts the short URL identifier and delegates to the repository
     * to retrieve the corresponding original URL.
     * </p>
     *
     * @param shortUrl the shortened URL identifier (without domain prefix)
     * @return the original long URL
     * @throws IllegalArgumentException if the short URL is not found
     */
    public String getLongUrl(String shortUrl)
    {
        return shortenerRepository.getLongUrl(shortUrl);
    }
}
